### ISSUE TITLE
MASTER bug: 2.0 commands

### ISSUE THREAD

**Issue by pmatulis** [juju/docs#901]
This is the master bug for tracking the ramifications the [new juju 2.0 commands](https://github.com/juju/docs/blob/master/src/en/command-changes.md) will have.

- [ ] Review/convert all pages to new Juju 2.0 commands ( #857 )
- [ ] Need an old command -> new command conversion guide ( #827 )
- [ ] Write help output for new Juju 2.0 commands ( #900 )

**Comment by matthewhelmke** [comment]
Superceded by #1361
